export const data=[
    {id:1 ,title:"hello world 1"},
    {id:2 ,title:"hello world 2"},
    {id:3 ,title:"hello world 3"},
    {id:4 ,title:"hello world 4"},
    {id:5 ,title:"hello world 5"},
    {id:6 ,title:"hello world 6"},
    {id:7 ,title:"hello world 7"},
    {id:8 ,title:"hello world 8"},
    {id:9 ,title:"hello world 9"},
    {id:10 ,title:"hello world 10"},
    {id:11 ,title:"hello world 11"},
    {id:12 ,title:"hello world 12"},
    {id:13 ,title:"hello world 13"},
    {id:14 ,title:"hello world 14"},    
    {id:15 ,title:"hello world 15"},
    {id:16 ,title:"hello world 16"},
    {id:17 ,title:"hello world 17"},
    {id:18 ,title:"hello world 18"},
    {id:19 ,title:"hello world 19"},
    {id:20 ,title:"hello world 20"},
    {id:21 ,title:"hello world 21"},
    {id:22 ,title:"hello world 22"},
    {id:23 ,title:"hello world 23"},
    {id:24 ,title:"hello world 24"},
    {id:25,title:"hello world 25"},
    {id:26 ,title:"hello world 26"},
    {id:27 ,title:"hello world 27"},
    {id:28,title:"hello world 28"},
    {id:29,title:"hello world 29"},
    {id:30 ,title:"hello world 30"},
    {id:31,title:"hello world 31"},
    {id:32,title:"hello world 32"},
    {id:33,title:"hello world 33"},
    {id:34,title:"hello world 34"},
    {id:35,title:"hello world 35"},
    {id:36,title:"hello world 36"},
    {id:37,title:"hello world 37"},
    {id:38,title:"hello world 38"},
    {id:39,title:"hello world 39"},
    {id:40,title:"hello world 40"},
    
]